### ISSUE TITLE
invoice Summary - foreignCurrency - doplnění

### ISSUE THREAD

**Issue by kargerova** [Salamek/pohoda#1]
Ahoj, v první řadě děkuju za použitelný modul na faktury. Dlužím za něj minimálně pozvání na pivo nebo na oběd ☺☺
Při generování faktur v cizí měně číhá v Summary.py (pohoda.entity.invoice.Summary.py) malý bug, díky kterému se nevygeneruje v xml korektně faktura v cizí měně - chybí summary. Test je napsaný tak šikovně, že to jím projde.

invoice.Summary.py
row 19:  data['foreignCurrency'] = CurrencyForeign(data, ico)
**bude fungovat se změnou na
row 19:  data['foreignCurrency'] = CurrencyForeign(data['foreignCurrency'], ico)**

Test:
pohoda/tests/entity/test_invoice.py
row 218: <inv:foreignCurrency/>

Děkuju a přeju hezký den!

**Comment by Salamek** [comment]
@kargerova  diky za report, opraveno
