### ISSUE TITLE
Jaká je předpokládaná konfigurace IS Pohoda v rámci zdárného použití této knihovny?

### ISSUE THREAD

**Issue by suvreal** [Salamek/pohoda#5]
Předem, děkuji za Vámi poskytuté řešení. Napadlo mě, že bych zkusil s IS Pohoda komunikovat skrze Python, původně jsem chtěl knihovnu napsat sám, ale to bylo předtím, než jsem tento repozitář nalezl. 
Jaké je tedy prosím nutné nastavení IS Pohoda pro zdárnou komunikaci - import a export? Má být nastaven mServer a spuštěn? V konfiguraci programu, tedy například zde: pohoda = Pohoda('65465454', 'a55', 'Export stock') má být tedy IČO, ID XML elementu a poznámka? Co z toho je nutné? Co dále má být nastaveno? Aplikace sama kontaktuje IS Pohoda nebo jen generuje filtry? A pokud aplikace komunikuje s IS Pohoda, kde se nastavuje přístup k HTTP IS Pohoda mServer jako takovému? Jaké všechny entity mohu tímto programem importovat a exportovat?
Vím, že se jedná o více dotazů, ale snažím se idetifikovat použitelnost, která je pro mě naprosto kruciální. Ještě jednou děkuji.

**Comment by Salamek** [comment]
Tato knihovna je prakticky glorifikovany generator XML s ~testy, zakaznici importuji vygenerovane XML rucne do Pohody, v pouziti s mServerem predpokladam ze se budou delat POST requesty na nejakou URL s HTTP auth kde `body` bude ono vygenerovane XML neco jako (mServer jsem nikdy nevidel v provozu) : 

```python
import io
import requests
from requests.auth import HTTPBasicAuth
from pohoda.Pohoda import Pohoda

pohoda = Pohoda('ICO', 'e_zas1', 'Export stock')


request = pohoda.create_list_request({
    'type': 'Stock'
})

# optional filter
request.add_user_filter_name('MyFilter')

pohoda.add_item('Export 001', request)

buffer = io.BytesIO()
pohoda.write(buffer)
buffer.seek(0)
xml = buffer.readvalue()

headers = {'Content-Type': 'application/xml'}
response = requests.post(
    'http://mserver.cz', 
    data=xml, 
    headers=headers,
    auth=HTTPBasicAuth(user, password)
)
# response.body Do XML nebo json parseru...
```
Seznam entit s kterymi muzete pracovat jsou zde (*.py) https://github.com/Salamek/pohoda/tree/master/pohoda/entity

Upozornuji ze otestovana agenda jsou "pouze" tyto testy https://github.com/Salamek/pohoda/tree/master/tests/entity ostatni jsou implementovane ale neotestovane (funkcnost nezarucena, pisu testy "on demand")

Dale neni implementovany parser, implementace on demand (zatim to nikdo nepotreboval)

**Comment by suvreal** [comment]
Děkuji za odpověď takto rychle a v sobotu :). Kód popřípadě použiji a děkuji rovnež i za linky. Chtěl bych jen upozornit na to, že ona XML - filtry i s příklady odpovědí má Stormware oficiálně na svých webových stránkách: https://www.stormware.cz/pohoda/xml/dokladyexport/ a https://www.stormware.cz/pohoda/xml/dokladyimport/, takže podle mého názoru není potřeba generátoru XML filtrů.

**Comment by Salamek** [comment]
> htěl bych jen upozornit na to, že ona XML - filtry i s příklady odpovědí má Stormware oficiálně na svých webových stránkách: https://www.stormware.cz/pohoda/xml/dokladyexport/ a https://www.stormware.cz/pohoda/xml/dokladyimport/, takže podle mého názoru není potřeba generátoru XML filtrů.

Rvat XML primo do kodu je prasarna, hlavne to neresi validaci, prevadeni objektu na jejich str reprezentaci, neni to testovatelne...

**Comment by suvreal** [comment]
Děkuji za komentář, nemyslel jsem to však diskvalifikačně. Myslel jsem to tak, že ty filtry už oficiálně existují a jsou připravené, načež se dají dále zpracovávat a obohacovat o dynamické úpravy. Ano, uznávám, že je elegantní to vytvářet s objektu a dále používat, ale ne všechna funkční použití jsou elegantní (bohužel).
